export const ENGINE_CONFIG = {
  MAX_SETTLEMENT_DAYS: 2,
  STALE_THRESHOLD_DAYS: 3,
  CRITICAL_THRESHOLD_DAYS: 7,
  ROUNDING_TOLERANCE: 0.05,
  HIGH_RISK_AMOUNT: 500,
  MEDIUM_RISK_AMOUNT: 100,
  ENGINE_VERSION: '1.0.3',
  SUPPORTED_CURRENCIES: ['GBP'],
};
